name: 'Terraform'

on:
 workflow_dispatch:

jobs:
  terraform:
    name: terraform-runner
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: 1.0.9
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1                                    # region where you want to deploy your infra
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.bucket_name }}" -backend-config="key=${{ secrets.key }}" -backend-config="region=${{ secrets.region_name }}" -input=false
        
      - name: Terraform Plan
        run: terraform plan -input=false -no-color
        continue-on-error: true
          
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        
