name: 'Terraform'

on:
 workflow_dispatch:

jobs:
  terraform:
    name: terraform-runner
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: 1.0.9
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1                                    # region where you want to deploy your infra
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Run Initaial setup
        uses: virtuecloud/Composite-actions/ShellScript-Run-Action@test
        with:
          FILENAME: initial_setup.sh
          CLIENTNAME: ${{ secrets.CLIENT_NAME }} 
          
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
          
      - name: Terraform Init
        uses: virtuecloud/Composite-actions/Terraform/TerraformInit@main
        with:
          STATE_LOCK: true
          STATE_BUCKET: ${{ secrets.BUCKET_NAME }}
          STATE_KEY: ${{ secrets.KEY }}
          REGION: ${{ secrets.BUCKET_REGION }}
          ENVIRONMENT: ${BRANCH_NAME}
          STATE_LOCK_TABLE: ${{ secrets.TABLE_NAME }}          
          
      - name: Terraform Plan
        uses: virtuecloud/Composite-actions/Terraform/TerraformPlan@main
          
      - name: Terraform Apply
        uses: virtuecloud/Composite-actions/Terraform/TerraformApply@main
        
