name: 'Terraform'

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  terraform:
    name: terraform-runner
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        path:
          - dev
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: 1.0.9
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1                                    # region where you want to deploy your infra
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Run Initaial setup
        uses: virtuecloud/Composite-actions/ShellScript-Run-Action@test
        with:
          STATE_LOCK: false
          STATE_BUCKET: ${{ secrets.BUCKET_NAME }}

      - name: Terraform Init
        uses: virtuecloud/Composite-actions/Terraform/TerraformInit@main
        with:
          FILENAME: initial_setup.sh
          CLIENTNAME: ${{ secrets.CLIENT_NAME }}
          
      - name: Terraform Plan
        uses: virtuecloud/Composite-actions/Terraform/TerraformPlan@main
        

