name: 'Terraform'

on:
  push:
    branches:
      - main
    inputs:
     bucket_name:
      description: 'name of the bucket'
      required: true
     region_name:
      description: 'region where bucket exists'
      required: true
      default: 'us-east-1'
     key: 
      description: 'name of file'
      required: true
        
  pull_request:
    branches:
      - main
    types: [closed]
    inputs:
       bucket_name:
        description: 'name of the bucket'
        required: true
       region_name:
        description: 'region where bucket exists'
        required: true
        default: 'us-east-1'
       key: 
        description: 'name of file'
        required: true

jobs:
  terraform:
    name: terraform-runner
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: 1.0.9
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1                                    # region where you want to deploy your infra
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ github.event.inputs.bucket_name }}" -backend-config="key=${{ github.event.inputs.key }}" -backend-config="region=${{ github.event.inputs.region_name }}" -input=false        
      - name: Terraform Plan
        run: terraform plan -input=false -no-color
        continue-on-error: true
        

